from setuptools import setup

packages = ["prosit_io", "prosit_io.file", "prosit_io.raw", "prosit_io.search_result", "prosit_io.spectral_library"]

package_data = {
    "": ["*"],
    "prosit_io.raw": ["utils/ThermoRawFileParser/*"],
    "prosit_io.spectral_library": ["dlib/*", "msp/*", "spectronaut/*"],
}

install_requires = [
    "fundamentals @ " "git+ssh://git@gitlab.lrz.de/compmass/prosit/tools/fundamentals.git@develop",
    "h5py>=3.3.0,<4.0.0",
    "numpy>=1.21.0,<2.0.0",
    "pandas>=1.3.0,<2.0.0",
    "pymzml>=2.5.0,<3.0.0",
    "pyteomics>=4.3.3",
    "lxml>=4.5.2",
]

setup_kwargs = {
    "name": "prosit-io",
    "version": "0.1.0",
    "description": "Handle IO operations for Oktoberfest",
    "long_description": None,
    "author": "WassimG",
    "author_email": "wassim.gabriel@tum.de",
    "maintainer": None,
    "maintainer_email": None,
    "url": None,
    "packages": packages,
    "package_data": package_data,
    "install_requires": install_requires,
    "python_requires": ">=3.8,<4.0",
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
