# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['io', 'io.file', 'io.search_result', 'io.spectral_library']

package_data = \
{'': ['*']}

install_requires = \
['h5py>=3.3.0,<4.0.0', 'numpy>=1.21.0,<2.0.0', 'pandas>=1.3.0,<2.0.0']

setup_kwargs = {
    'name': 'io',
    'version': '0.1.0',
    'description': 'Handle IO operations for Oktoberfest',
    'long_description': None,
    'author': 'WassimG',
    'author_email': 'wassim.gabriel@tum.de',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
