# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['spectrum_io',
 'spectrum_io.file',
 'spectrum_io.raw',
 'spectrum_io.search_result',
 'spectrum_io.spectral_library']

package_data = \
{'': ['*'],
 'spectrum_io.raw': ['utils/ThermoRawFileParser/*'],
 'spectrum_io.spectral_library': ['dlib/*', 'msp/*', 'spectronaut/*']}

install_requires = \
['PyYAML>=5.4.1',
 'click>=8.0.0',
 'h5py>=3.1.0,<4.0.0',
 'lxml>=4.5.2,<5.0.0',
 'numpy>=1.18.1,<2.0.0',
 'pandas>=1.3.0,<2.0.0',
 'pymzml>=2.5.0,<3.0.0',
 'pyteomics>=4.3.3,<5.0.0',
 'rich>=10.3.0',
 'spectrum-fundamentals>=0.3.0,<0.4.0',
 'tables>=3.6.1,<4.0.0']

entry_points = \
{'console_scripts': ['spectrum_io = spectrum_io.__main__:main']}

setup_kwargs = {
    'name': 'spectrum-io',
    'version': '0.1.0',
    'description': 'IO related functionalities for oktoberfest.',
    'long_description': 'spectrum_io\n===========================\n\n|PyPI| |Python Version| |License| |Read the Docs| |Build| |Tests| |Codecov| |pre-commit| |Black|\n\n.. |PyPI| image:: https://img.shields.io/pypi/v/spectrum_io.svg\n   :target: https://pypi.org/project/spectrum_io/\n   :alt: PyPI\n.. |Python Version| image:: https://img.shields.io/pypi/pyversions/spectrum_io\n   :target: https://pypi.org/project/spectrum_io\n   :alt: Python Version\n.. |License| image:: https://img.shields.io/github/license/wilhelm-lab/spectrum_io\n   :target: https://opensource.org/licenses/MIT\n   :alt: License\n.. |Read the Docs| image:: https://img.shields.io/readthedocs/spectrum_io/latest.svg?label=Read%20the%20Docs\n   :target: https://spectrum_io.readthedocs.io/\n   :alt: Read the documentation at https://spectrum_io.readthedocs.io/\n.. |Build| image:: https://github.com/wilhelm-lab/spectrum_io/workflows/Build%20spectrum_io%20Package/badge.svg\n   :target: https://github.com/wilhelm-lab/spectrum_io/actions?workflow=Package\n   :alt: Build Package Status\n.. |Tests| image:: https://github.com/wilhelm-lab/spectrum_io/workflows/Run%20spectrum_io%20Tests/badge.svg\n   :target: https://github.com/wilhelm-lab/spectrum_io/actions?workflow=Tests\n   :alt: Run Tests Status\n.. |Codecov| image:: https://codecov.io/gh/wilhelm-lab/spectrum_io/branch/master/graph/badge.svg\n   :target: https://codecov.io/gh/wilhelm-lab/spectrum_io\n   :alt: Codecov\n.. |pre-commit| image:: https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white\n   :target: https://github.com/pre-commit/pre-commit\n   :alt: pre-commit\n.. |Black| image:: https://img.shields.io/badge/code%20style-black-000000.svg\n   :target: https://github.com/psf/black\n   :alt: Black\n\n\nFeatures\n--------\n\n* TODO\n\n\nInstallation\n------------\n\nYou can install *spectrum_io* via pip_ from PyPI_:\n\n.. code:: console\n\n   $ pip install spectrum_io\n\n\nUsage\n-----\n\nPlease see the `Command-line Reference <Usage_>`_ for details.\n\n\nCredits\n-------\n\nThis package was created with cookietemple_ using Cookiecutter_ based on Hypermodern_Python_Cookiecutter_.\n\n.. _cookietemple: https://cookietemple.com\n.. _Cookiecutter: https://github.com/audreyr/cookiecutter\n.. _PyPI: https://pypi.org/\n.. _Hypermodern_Python_Cookiecutter: https://github.com/cjolowicz/cookiecutter-hypermodern-python\n.. _pip: https://pip.pypa.io/\n.. _Usage: https://spectrum_io.readthedocs.io/en/latest/usage.html\n',
    'author': 'Mario Picciani',
    'author_email': 'mario.picciani@tum.de',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://github.com/wilhelm-lab/spectrum_io',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.8.0,<4.0.0',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
